- name: Pull Docker image
  hosts: all
  become: true
  tasks:
    # paleidžiam dockerį
    - name: Start docker service
      service:
        name: docker
        state: started
        enabled: true
    # Pullinam API appso image'ą iš dockerio repo
    - name: Pull the API app Docker image
      command: docker pull karabasas/my-api-app
      register: pull_result
    # sustabdom ir pašalinam betkokį veikiantį konteinerį su veikiančiu API
    - name: Remove existing API running containers
      docker_container:
        name: my-api-app
        state: absent
    # paleidžiam API konteinerį
    - name: Start API app Docker container
      docker_container:
        name: my-api-app
        image: karabasas/my-api-app:latest
        state: started
        ports:
          - "5000:5000" # mapinam ec2 instance 5000 portą su konteinerio 5000 portu
        restart_policy: always
        env:
          AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
          AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
          AWS_REGION: "{{ lookup('env', 'AWS_REGION') }}"
        restart: true
    # išsivedam ar sėkmingai pavyko paleisti konteinerį
    - name: Display pull result
      debug:
        var: pull_result.stdout

    - name: Display API app container status
      debug:
        msg: >
          The API app container is running with the following details: {{ container_status.stdout }}
