name: Deploy API app on VM with Ansible

on: 
    workflow_dispatch:
        inputs:
            vm_ip:
                description: Enter the IP of the VM (again)
                required: true
                default: "your.vm.ip.here"

jobs:
    install_api_app:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./Ansible_playbooks
        steps:
            
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Create SSH directory
              run: mkdir -p ~/.ssh

            - name: Add host to known hosts
              run: ssh-keyscan -H ${{ github.event.inputs.vm_ip }} > ~/.ssh/known_hosts

            - name: Check and install Ansible
              run: |
                if ! command -v ansible &> /dev/null; then
                  echo "Ansible not found. Installing..."
                  sudo apt-get update && sudo apt-get install -y ansible
                else
                  echo "Ansible already installed"
                fi

            - name: Ensure everything is up to date
              run: |
                sudo dpkg --configure -a
                sudo apt-get update --fix-missing
                sudo apt-get -f install

            - name: Setup SSH key to connect to EC2 VM
              run: |
                mkdir -p ~/.ssh
                echo "${{ secrets.AWS_SSH_KEY }}" > ~/.ssh/id_rsa
                chmod 600 ~/.ssh/id_rsa

            - name: Set AWS Credentials
              run: |
                echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.bash_profile
                echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.bash_profile
                echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> ~/.bash_profile
              env:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                AWS_REGION: eu-central-1

            - name: Run the playbook to deploy the API
              run: |
                ansible-playbook -u ubuntu -i ${{ github.event.inputs.vm_ip }}, --private-key ~/.ssh/id_rsa API_on_docker_on_vm.yml
              env:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                AWS_REGION: eu-central-1

            - name: SSH into VM to check deployment success
              run: |
                VM_IP_DASHED=$(echo ${{ github.event.inputs.vm_ip }} | tr '.' '-')
                ssh -i ${{ secrets.AWS_SSH_KEY }} ubuntu@ec2-${VM_IP_DASHED}.eu-central-1.compute.amazon.com "docker ps"
