name: Deploy API app on VM with Ansible

on: 
    workflow_dispatch:
        inputs:
            environment:
                type: choice
                description: READY?? SET?? GO!!
                options:
                    - GOGOx2
                default: Going
    workflow_run:
        workflows:
            - Setup DOcker on VM with Ansible
        types:
            - completed

jobs:
    install_api_app:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./Ansible_playbooks
        steps:
            
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Download VM IP artifact from previous workflow
              uses: actions/download-artifact@v3
              with:
                  name: vm-ip
              if: ${{ inputs.vm_ip == '' }}

            - name: Set VM IP from input (if provided)
              run: echo "VM_IP=${{ github.event.inputs.vm_ip }}" >> $GITHUB_ENV
              if: ${{ inputs.vm_ip != '' }}

            - name: Create SSH directory
              run: mkdir -p ~/.ssh

            - name: Add host to known hosts
              run: ssh-keyscan -H ${{ env.VM_IP }} > ~/.ssh/known_hosts

            - name: Check and install Ansible
              run: |
                if ! command -v ansible &> /dev/null; then
                  echo "Ansible not found. Installing..."
                  sudo apt-get update && sudo apt-get install -y ansible
                else
                  echo "Ansible already installed"
                fi

            - name: Ensure everything is up to date
              run: |
                sudo dpkg --configure -a
                sudo apt-get update --fix-missing
                sudo apt-get -f install

            - name: Setup SSH key to connect to EC2 VM
              run: |
                mkdir -p ~/.ssh
                echo "${{ secrets.AWS_SSH_KEY }}" > ~/.ssh/id_rsa
                chmod 600 ~/.ssh/id_rsa

            - name: Run the playbook to deploy the API
              run: ansible-playbook -u ubuntu -i ${{ env.VM_IP }}, --private-key ~/.ssh/id_rsa API_on_docker_on_vm.yml
