name: Deploy Task Manager to EC2

on:
    workflow_dispatch:
        inputs:
            environment:
                type: choice
                description: Ready, set, go!
                options:
                    - GOGOGO
                default: Go

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Create directory for SSH
              run: mkdir -p ~/.ssh

            - name: Add host to list of known hosts
              run: ssh-keyscan -H 3.73.178.155 > ~/.ssh/known_hosts

            - name: Set up Ansible
              run: |
                sudo apt-get update
                sudo apt-get install -y ansible

            - name: Set SSH connection to the EC2 instance
              run: |
                mkdir -p ~/.ssh
                echo "${{ secrets.AWS_SSH_KEY }}" > ~/.ssh/id_rsa
                chmod 600 ~/.ssh/id_rsa
                

            - name: Run Ansible playbook
              run: |
                ansible-playbook -u ubuntu -i 3.73.178.155, --private-key ~/.ssh/id_rsa task_manager_deploy.yml

