name: Python Tests

on:
    workflow_dispatch:
        inputs:
            vm_ip:
                description: 'IP of the VM to run tests on'
                required: true
                default: 'Testing VM IP here'
            unit_tests:
                description: 'Comma-separated list of unit tests to run'
                required: true
                default: unit_test_1, unit_test_2'
            integration_tests:
                description: 'Comma-separated list of integration tests to run'
                required: true
                default: 'Integration_1, Integration_2'
            e2e_tests:
                description: 'Comma-separated list of e2e tests to run'
                required: true
                default: 'e2e_test_1, e2e_test_2'
jobs:
    run-tests:
        runs-on: ubuntu-latest

        steps:

            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.10'
        
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Run unit tests
              run: |
                pytest -k "${{ github.event.inputs.unit_tests }}" --base-url ${{ github.event.inputs.vm_ip }} | tee unit_tests_output.txt

            - name: Run Integration tests
              run: |
                pytest -k "${{ github.event.inputs.integration_tests }}" --base-url ${{ github.event.inputs.vm_ip }} | tee integration_tests_output.txt

            - name: Run e2e tests
              run: |
                pytest -k "${{ github.event.inputs.e2e_tests }}" --base-url ${{ github.event.inputs.vm_ip }} | tee e2e_tests_output.txt

            - name: Upload results to cloudwatch
              env:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
              run: |
                aws logs create-log-group --log-group-name /github/actions/tests
                aws logs create-log-stream --log-group-name /github/actions/tests --log-stream-name unit_tests
                aws logs create-log-stream --log-group-name /github/actions/tests --log-stream-name integration_tests
                aws logs create-log-stream --log-group-name /github/actions/tests --log-stream-name e2e_tests
                aws logs put-log-events --log-group-name /github/actions/tests --log-stream-name unit_tests --log-events file://unit_tests_output.txt
                aws logs put-log-events --log-group-name /github/actions/tests --log-stream-name integration_tests --log-events file://integration_tests_output.txt
                aws logs put-log-events --log-group-name /github/actions/tests --log-stream-name e2e_tests --log-events file://e2e_tests_output.txt



        

        